#try: except: finally: except exception as ret: except (A and B): alse: raise some:
class Except_test():
	def except_play(self):
		try:
			print(self.__name)
			return name
		except (NameError and AttributeError):
			print('出错')

A=Except_test()
A.except_play()